name: ci
on: [push, pull_request]
jobs:
  tests1:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎
        uses: actions/checkout@v6

      - name: Node version 🖨️
        run: node -v

      - name: NPM install
        uses: bahmutov/npm-install@v1

      - name: Run tests 🧪
        run: npm test

      - name: Run demo 1 📊
        run: npm run demo

      - name: Run demo 2 📊
        run: npm run demo2

      - name: Run demo 3 📊
        run: npm run demo3

      - name: Run demo 4 📊
        run: npm run demo4

      - name: Run demo 5 📊
        run: npm run demo5

      - name: Run demo 6 📊
        run: npm run demo6

      - name: Run demo 7 📊
        run: npm run demo7

  tests2:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎
        uses: actions/checkout@v6

      - name: Node version 🖨️
        run: node -v

      - name: NPM install
        uses: bahmutov/npm-install@v1
      # hmm why are some demos skipped?

      - name: Run demo 11 📊
        run: npm run demo11

      - name: Run demo 12 📊
        run: npm run demo12

      - name: Run demo 9 📊
        run: START_SERVER_AND_TEST_INSECURE=1 npm run demo9

      - name: Run demo cross env 📊
        run: npm run demo-cross-env

      - name: Run demo commands 📊
        run: npm run demo-commands

      - name: Run demo multiple 📊
        run: npm run demo-multiple

      - name: Run demo expect 403 code 📊
        run: npm run demo-expect-403

  tests-node-v22:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎
        uses: actions/checkout@v6

      - uses: actions/setup-node@v6
        with:
          node-version: 22

      - name: Node version 🖨️
        run: node -v

      - name: NPM install
        uses: bahmutov/npm-install@v1

      - name: Run json-server test
        run: npm run demo-json-server

      - name: Run explicit 0.0.0.0 host example
        run: npm run demo-zero-explicit

      - name: Run 0.0.0.0 host with 127.0.0.1 url
        run: npm run demo-zero-127

      - name: Run 0.0.0.0 host example
        run: npm run demo-zero

  tests-node-v24:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎
        uses: actions/checkout@v6

      - uses: actions/setup-node@v6
        with:
          node-version: 24

      - name: Node version 🖨️
        run: node -v

      - name: NPM install
        uses: bahmutov/npm-install@v1

      - name: Run json-server test
        run: npm run demo-json-server

      - name: Run ::1 host example
        run: npm run demo-ip6

      - name: Run explicit 0.0.0.0 host example
        run: npm run demo-zero-explicit

      - name: Run 0.0.0.0 host with 127.0.0.1 url
        run: npm run demo-zero-127

      - name: Run 0.0.0.0 host example
        run: npm run demo-zero

  release:
    needs: ['tests1', 'tests2', 'tests-node-v22', 'tests-node-v24']
    # only release from the master branch
    # in parent repository, not in a fork
    if: (github.ref == 'refs/heads/master') &&
      (github.repository == 'bahmutov/start-server-and-test')
    runs-on: ubuntu-latest
    permissions:
      # allow the release step to comment on
      # issues, pull requests, and write to the repo
      contents: write
      issues: write
      pull-requests: write
      # Required for OIDC to let NPM registry know
      # that this workflow is trusted
      id-token: write
    steps:
      # important: the default Node version is v20
      # which gives us an auth error trying to release
      # so install v24 explicitly
      - uses: actions/setup-node@v6
        with:
          node-version: 24

      - name: Checkout 🛎
        uses: actions/checkout@v6

      - name: Semantic Release 🚀
        uses: cycjimmy/semantic-release-action@v6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
